### ISSUE TITLE
Uniread Syntax Error

### ISSUE THREAD

**Issue by reclinqs** [nemanjan00/uniread#90]
firstly, i am using a ubuntu based linux distro
i have installed npm via apt package manager
and i have also applied commands properly as given instructions

but i am having this error every time i reinstall two packages one by one and launch uniread:
```

/usr/local/lib/node_modules/uniread/node_modules/marked-terminal/index.cjs:333
			&& Number(osRelease[2]) >= 10_586
			                           ^^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/uniread/node_modules/blessed-contrib/lib/widget/markdown.js:5:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
 
```

**Comment by nemanjan00** [comment]
Fixed
